import * as Knex from "knex";


export async function up(knex: Knex): Promise<any> {
  return knex.schema.raw(`
    CREATE TABLE m.masky(
        "id" int not null PRIMARY KEY,
        "nazov" char(30) not null,
        "skratka" char(10) not null,
        "skupina_zobrazenia" int not null,
        "pozicia" int not null,
        "n1" int not null,
        "n2" int not null,
        "n3" int not null,
        "n4" int not null,
        "n5" int not null,
        "n6" int not null,
        "n7" int not null,
        "n8" int not null,
        "n9" int not null,
        "n10" int not null,
        "n11" int not null,
        "n12" int not null,
        "n13" int not null,
        "n14" int not null,
        "n15" int not null,
        "n16" int not null,
        "n17" int not null,
        "n18" int not null,
        "n19" int not null,
        "n20" int not null,
        "n21" int not null,
        "n22" int not null,
        "n23" int not null,
        "n24" int not null,
        "n25" int not null,
        "n26" int not null,
        "n27" int not null,
        "n28" int not null,
        "n29" int not null,
        "n30" int not null,
        "n31" int not null,
        "n32" int not null,
        "n33" int not null,
        "n34" int not null,
        "n35" int not null,
        "n36" int not null,
        "n37" int not null,
        "n38" int not null,
        "n39" int not null,
        "n40" int not null,
        "n41" int not null,
        "n42" int not null,
        "n43" int not null,
        "n44" int not null,
        "n45" int not null,
        "n46" int not null,
        "n47" int not null,
        "n48" int not null,
        "n49" int not null,
        "n50" int not null,
        "n51" int not null,
        "n52" int not null,
        "n53" int not null,
        "n54" int not null,
        "n55" int not null,
        "n56" int not null,
        "n57" int not null,
        "n58" int not null,
        "n59" int not null,
        "n60" int not null,
        "n61" int not null,
        "n62" int not null,
        "n63" int not null,
        "n64" int not null,
        "n65" int not null,
        "n66" int not null,
        "n67" int not null,
        "n68" int not null,
        "n69" int not null,
        "n70" int not null,
        "n71" int not null,
        "n72" int not null,
        "n73" int not null,
        "n74" int not null,
        "n75" int not null,
        "n76" int not null,
        "n77" int not null,
        "n78" int not null,
        "n79" int not null,
        "n80" int not null,
        "n81" int not null,
        "n82" int not null,
        "n83" int not null,
        "n84" int not null,
        "n85" int not null,
        "n86" int not null,
        "n87" int not null,
        "n88" int not null,
        "n89" int not null,
        "n90" int not null,
        "n91" int not null,
        "n92" int not null,
        "n93" int not null,
        "n94" int not null,
        "n95" int not null,
        "n96" int not null,
        "n97" int not null,
        "n98" int not null,
        "n99" int not null,
        "n100" int not null,
        "z1" int not null,
        "z2" int not null,
        "z3" int not null,
        "z4" int not null,
        "z5" int not null,
        "z6" int not null,
        "z7" int not null,
        "z8" int not null,
        "z9" int not null,
        "z10" int not null,
        "z11" int not null,
        "z12" int not null,
        "z13" int not null,
        "z14" int not null,
        "z15" int not null,
        "z16" int not null,
        "z17" int not null,
        "z18" int not null,
        "z19" int not null,
        "z20" int not null,
        "z21" int not null,
        "z22" int not null,
        "z23" int not null,
        "z24" int not null,
        "z25" int not null,
        "z26" int not null,
        "z27" int not null,
        "z28" int not null,
        "z29" int not null,
        "z30" int not null,
        "z31" int not null,
        "z32" int not null,
        "z33" int not null,
        "z34" int not null,
        "z35" int not null,
        "z36" int not null,
        "z37" int not null,
        "z38" int not null,
        "z39" int not null,
        "z40" int not null,
        "z41" int not null,
        "z42" int not null,
        "z43" int not null,
        "z44" int not null,
        "z45" int not null,
        "z46" int not null,
        "z47" int not null,
        "z48" int not null,
        "z49" int not null,
        "z50" int not null,
        "format" char(1) not null
      );
      COMMENT ON TABLE m.masky IS 'Tabulka obsahuje pozicie, podla ktorych sa napocitavaju definovane hodnoty z tabulky vypocet.vektor';
      COMMENT ON COLUMN m.masky.id IS 'poradove cislo zaznamu';
      COMMENT ON COLUMN m.masky.nazov  IS 'Popis riadka - napriklad Hruba mzda';
      COMMENT ON COLUMN m.masky.skratka  IS 'skratka napr.HM';
      COMMENT ON COLUMN m.masky.skupina_zobrazenia  IS 'oznacenie skupiny riadkov, ktore patria vyznamovo k sebe';
      COMMENT ON COLUMN m.masky.pozicia  IS 'pozicia v danej skupine zobrazenia';
      COMMENT ON COLUMN m.masky.n1 IS '  obsahuje cislo pozicie pre napocet z vektora vypocitanych udajov (sumy z pozicie nXXX sa pripocitavaju)';
      COMMENT ON COLUMN m.masky.z1 IS '  obsahuje cislo pozicie pre napocet z vektora vypocitanych udajov (sumy z pozicie zXX sa odpocitavaju)';      
      `)

}


export async function down(knex: Knex): Promise<any> {
  return knex.raw(`DROP TABLE m.masky;`);
}

